[package]
name = "reth-interfaces"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"

[dependencies]
reth-codecs = { path = "../storage/codecs" }
reth-primitives = { path = "../primitives" }
reth-rpc-types = { path = "../rpc/rpc-types" }
reth-network-api = { path = "../net/network-api" }
# TODO(onbjerg): We only need this for [BlockBody]
reth-eth-wire = { path = "../net/eth-wire" }

# eth
revm-primitives = "1.1"
parity-scale-codec = { version = "3.2.1", features = ["bytes"] }

# async
async-trait = "0.1.57"
futures = "0.3"
tokio = { version = "1.21.2", features = ["sync"] }
tokio-stream = "0.1.11"

# misc
auto_impl = "1.0"
thiserror = "1.0.37"
tracing = { workspace = true }
rand = "0.8.5"
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
secp256k1 = { version = "0.27.0", default-features = false, features = [
    "alloc",
    "recovery",
    "rand",
], optional = true }
modular-bitfield = "0.11.2"
parking_lot = "0.12.1"

[dev-dependencies]
reth-db = { path = "../storage/db", features = ["test-utils"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["sync"] }
arbitrary = { version = "1.1.7", features = ["derive"] }
hex-literal = "0.3"
secp256k1 = { version = "0.27.0", default-features = false, features = [
    "alloc",
    "recovery",
    "rand",
] }

[features]
bench = []
test-utils = ["tokio-stream/sync", "secp256k1"]
