[package]
name = "ef-tests"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Staged syncing primitives used in reth."

[features]
ef-tests = []

[dependencies]
reth-primitives = { path = "../../crates/primitives" }
reth-db = { path = "../../crates/storage/db", features = ["mdbx", "test-utils"] }
reth-provider = { path = "../../crates/storage/provider" }
reth-stages = { path = "../../crates/stages" }
reth-rlp = { path = "../../crates/rlp" }
reth-interfaces = { path = "../../crates/interfaces" }
reth-revm = { path = "../../crates/revm" }
tokio = "1.28.1"
walkdir = "2.3.3"
serde = "1.0.163"
serde_json = "1.0.96"
thiserror = "1.0.40"