[package]
name = "reth-provider"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Reth storage provider."

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-interfaces = { path = "../../interfaces" }
reth-revm-primitives = { path = "../../revm/revm-primitives" }
reth-db = { path = "../db" }
reth-trie = { path = "../../trie" }

# async
tokio = { version = "1.21", features = ["sync", "macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["sync"] }

# tracing
tracing = { workspace = true }

# misc
thiserror = "1.0.37"
auto_impl = "1.0"
itertools = "0.10"
pin-project = "1.0"
derive_more = "0.99"
parking_lot = "0.12"

# test-utils
reth-rlp = { path = "../../rlp", optional = true }

[dev-dependencies]
reth-db = { path = "../db", features = ["test-utils"] }
reth-primitives = { path = "../../primitives", features = ["arbitrary", "test-utils"] }
reth-rlp = { path = "../../rlp" }
reth-trie = { path = "../../trie", features = ["test-utils"] }
parking_lot = "0.12"

[features]
bench = []
test-utils = ["reth-rlp"]
