[package]
name = "reth-tasks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Task management"

[dependencies]

## async
tokio = { version = "1", features = ["sync", "rt"] }
tracing-futures = "0.2"
futures-util = "0.3"

## misc
tracing = { workspace = true }
thiserror = "1.0"
dyn-clone = "1.0"

## rpc/metrics
metrics = "0.20.1"
reth-metrics-derive = { path = "../metrics/metrics-derive" }

[dev-dependencies]
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "time", "macros"] }
