[package]
name = "reth-rpc-engine-api"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
description = "Implementation of Engine API"

[dependencies]
# reth 
reth-primitives = { path = "../../primitives" }
reth-interfaces = { path = "../../interfaces" }
reth-provider = { path = "../../storage/provider" }
reth-rpc-types = { path = "../rpc-types" }
reth-rpc-api = { path = "../rpc-api" }
reth-beacon-consensus = { path = "../../consensus/beacon" }
reth-payload-builder = { path = "../../payload/builder" }

# async
tokio = { version = "1", features = ["sync"] }

# misc
async-trait = "0.1"
thiserror = "1.0.37"
jsonrpsee-types = "0.16"
jsonrpsee-core = "0.16"
tracing = "0.1"

[dev-dependencies]
reth-interfaces = { path = "../../interfaces", features = ["test-utils"] }
reth-provider = { path = "../../storage/provider", features = ["test-utils"] }
reth-payload-builder = { path = "../../payload/builder", features = ["test-utils"] }
assert_matches = "1.5.0"
